name: Bug Report
description: "Report something that's broken."
body:
  - type: input
    attributes:
      label: Repository Version
      description: Provide the repository version that you are using.
      placeholder: 1.52.0
    validations:
      required: true
  - type: input
    attributes:
      label: Node.js Version
      description: Provide the Node version that you are using.
      placeholder: 8.1.4
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Provide a detailed description of the issue you are facing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Provide detailed steps to reproduce your issue.
    validations:
      required: true
