blank_issues_enabled: false
contact_links:
  - name: Support Questions & Other
    url: povly19995@gmail.com
    about: 'This repository is only for reporting bugs. If you have a question or need help using the library, click:'
