blank_issues_enabled: false
contact_links:
  - name: Support Questions & Other
    url: https://t.me/povly
    about: 'This repository is only for reporting bugs. If you have a question or need help using the library, click:'
